window.STUDY_AUDIO_FILES = {
  "Afghanistan": true,
  "Albania": true,
  "Argentina": true,
  "Armenia": true,
  "Australia": true,
  "Azerbaijan": true,
  "Bangladesh": true,
  "Belarus": true,
  "Belgium": true,
  "Bhutan": true,
  "Bolivia": true,
  "Bosnia Herzegovina": true,
  "Brazil": true,
  "Bulgaria": true,
  "Burnei": true,
  "Cambodia": true,
  "Canada": true,
  "Chad": true,
  "Chile": true,
  "China": true,
  "Colombia": true,
  "Croatia": true,
  "Cuba": true,
  "Czech Republic": true,
  "Denmark": true,
  "Egypt": true,
  "Estonia": true,
  "Ethiopia": true,
  "Finland": true,
  "France": true,
  "Georgia": true,
  "Germany": true,
  "Greece": true,
  "Hungary": true,
  "Iceland": true,
  "India": true,
  "Indonesia": true,
  "Iran": true,
  "Iraq": true,
  "Ireland": true,
  "Israel": true,
  "Italy": true,
  "Jamaica": true,
  "Japan": true,
  "Jordan": true,
  "Kazakhstan": true,
  "Kenya": true,
  "Kyrgyzstan": true,
  "Laos": true,
  "Latvia": true,
  "Lithuania": true,
  "Luxembourg": true,
  "Madagascar": true,
  "Malaysia": true,
  "Maldives": true,
  "Malta": true,
  "Mexico": true,
  "Moldova": true,
  "Monaco": true,
  "Mongolia": true,
  "Morocco": true,
  "Myanmar": true,
  "Nepal": true,
  "Netherlands": true,
  "New Zealand": true,
  "Nicaragua": true,
  "Nigeria": true,
  "North Korea": true,
  "Norway": true,
  "Pakistan": true,
  "Panama": true,
  "Paraguay": true,
  "Peru": true,
  "Philippines": true,
  "Poland": true,
  "Portugal": true,
  "Qatar": true,
  "Romania": true,
  "Russian Federation": true,
  "Saudi Arabia": true,
  "Serbia": true,
  "Slovakia": true,
  "Slovenia": true,
  "South Africa": true,
  "South Korea": true,
  "Spain": true,
  "Sri Lanka": true,
  "Sweden": true,
  "Switzerland": true,
  "Syria": true,
  "Tajikistan": true,
  "Thailand": true,
  "Tonga": true,
  "Tunisia": true,
  "Turkey": true,
  "Turkmenistan": true,
  "Ukraine": true,
  "United Arab Emirates": true,
  "United Kingdom": true,
  "United States": true,
  "Urguay": true,
  "Uzbekistan": true,
  "Vietnam": true
};
